In [1]:
%pip install aps-toolkit --upgrade

Requirement already satisfied: aps-toolkit in c:\python311\lib\site-packages (0.0.8)
Requirement already satisfied: requests in c:\python311\lib\site-packages (from aps-toolkit) (2.31.0)
Requirement already satisfied: pandas in c:\python311\lib\site-packages (from aps-toolkit) (2.2.1)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\python311\lib\site-packages (from pandas->aps-toolkit) (1.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python311\lib\site-packages (from pandas->aps-toolkit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\python311\lib\site-packages (from pandas->aps-toolkit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\python311\lib\site-packages (from pandas->aps-toolkit) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests->aps-toolkit) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests->aps-toolkit) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests->aps-toolkit) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests->aps-toolkit) (2023.7.22)
Requirement already satisfied: six>=1.5 in c:\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas->aps-toolkit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
from aps_toolkit import Auth
import pandas as pd

In [14]:
token = Auth().auth2leg()

In [15]:
urn = "dXJuOmFkc2sud2lwcHJvZDpmcy5maWxlOnZmLjAtYnBtcEpXUWJTRUVNdUFac1VETWc_dmVyc2lvbj0yNQ"

In [16]:
from aps_toolkit import PropDbReaderRevit
prop_reader = PropDbReaderRevit(urn, token)

In [17]:
categories = prop_reader.get_all_categories()
# to dataframe with columns "dbid,category" from dict categories
df = pd.DataFrame.from_dict(categories, orient='index', columns=["category"])
df = df.reset_index()
df = df.rename(columns={"index":"dbid"})
df.head(20)

    dbid                category
0    111               Materials
1    425              Elevations
2    430                   Views
3    466        Primary Contours
4    480            Area Schemes
5    511                  Phases
6    577             Shared Site
7    616         Work Plane Grid
8    683                Revision
9    688     Project Information
10   716   Structural Load Cases
11   761                Sun Path
12   955         Internal Origin
13  1143                 Cameras
14  1148           Section Boxes
15  1255              HVAC Zones
16  1270       Color Fill Schema
17  1302     HVAC Load Schedules
18  1328  Building Type Settings
19  1362     Space Type Settings

In [18]:
families = prop_reader.get_all_families()
# to dataframe with columns "dbid,family" from dict families
df = pd.DataFrame.from_dict(families, orient='index', columns=["family"])
df = df.reset_index()
df = df.rename(columns={"index":"dbid"})
df.head(10)

    dbid         family
0   5013         Legend
1   6716          Sheet
2   6743  Drafting View
3   8426       Schedule
4  10301     Floor Plan
5    426      Elevation
6    431      Elevation
7  10297     Floor Plan
8  10552        Section
9    579       Internal

In [19]:
families_types = prop_reader.get_all_families_types()
# to dataframe with columns "dbid,family,type" from dict families_types
df = pd.DataFrame.from_dict(families_types, orient='index', columns=["family_type"])
df = df.reset_index()
df = df.rename(columns={"index":"dbid"})
df.head(10)

    dbid         family_type
0   5015              Legend
1   6718               Sheet
2   6745              Detail
3    428  Building Elevation
4  10299          Floor Plan
5  10554    Building Section
6    579       Location Data
7   1517       Location Data
8   1146             3D View
9   5023            Standard

In [20]:
df = prop_reader.get_data_by_category("Lines")
df.head()

,dbId,external_id,Workset,Edited by,Line Style,Detail Line,Length,Center Mark Visible
0,5025,fed25bcc-43b7-4a3d-9fc4-1221bb168f5d,NaN,NaN,NaN,NaN,NaN,NaN
1,5026,4cec1bb0-afe8-449c-99b9-3cb8e6b577d6-000a4311,"View ""Legend: TEMPERATURE CONTROL ZONING""",,<Thin Lines>,1.0,60.000000,NaN
2,5027,4cec1bb0-afe8-449c-99b9-3cb8e6b577d6-000a4312,"View ""Legend: TEMPERATURE CONTROL ZONING""",,<Thin Lines>,1.0,98.028473,NaN
3,5028,4cec1bb0-afe8-449c-99b9-3cb8e6b577d6-000a4313,"View ""Legend: TEMPERATURE CONTROL ZONING""",,<Thin Lines>,1.0,75.000000,NaN
4,5029,4cec1bb0-afe8-449c-99b9-3cb8e6b577d6-000a4314,"View ""Legend: TEMPERATURE CONTROL ZONING""",,<Thin Lines>,1.0,30.000000,NaN

In [21]:
prop_reader.get_data_by_categories_and_params(["Pipes","Ducts"], ["Width", "Height","Length","Workset"])

,dbId,external_id,Workset,Width,Height,Length
3,15901,650dac91-a97a-4182-b882-b1b294b266e3-001aaf9c,ex_M_HVAC_EA,450.0,450.0,380.0
4,15932,650dac91-a97a-4182-b882-b1b294b266e3-001ab1f3,ex_M_HVAC_FA,450.0,450.0,380.0
5,15952,650dac91-a97a-4182-b882-b1b294b266e3-001ab4e0,ex_M_HVAC_FA,450.0,450.0,380.0
6,15959,650dac91-a97a-4182-b882-b1b294b266e3-001ab4e7,ex_M_HVAC_FA,450.0,450.0,380.0
7,15988,650dac91-a97a-4182-b882-b1b294b266e3-001ab9c0,ex_M_HVAC_EA,450.0,450.0,380.0
...,...,...,...,...,...,...
578,16133,832478c1-3e5c-49fe-9776-ed1213f7a84f-001b4a50,ex_M_HVAC_EA,NaN,NaN,926.5
579,23280,f8ab7cba-776d-4ddc-81ce-de3c8c293aa6-0026cbbb,ex_M_HVAC_FA,NaN,NaN,100.0
580,23281,f8ab7cba-776d-4ddc-81ce-de3c8c293aa6-0026cbbc,ex_M_HVAC_FA,NaN,NaN,100.0
581,23314,d5519659-1830-49bb-b35d-b0ba03c5399f-0026e82d,ex_M_HVAC_FA,NaN,NaN,100.0
582,23315,d5519659-1830-49bb-b35d-b0ba03c5399f-0026e82e,ex_M_HVAC_FA,NaN,NaN,100.0

In [22]:
df = prop_reader.get_data_by_categories(["Pipes","Ducts"])
df.head()

,dbId,external_id,System Classification,System Type,System Name,System Abbreviation,Image,Free Size,Overall Size,Lining Thickness,...,Upper End Top Elevation,Middle Elevation,Lower End Bottom Elevation,Area,Length,Slope,Type Name,Upper End Centerline Elevation,Lower End Centerline Elevation,Diameter
0,15897,90dee50f-d93e-45b7-bc25-79fdad85659a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15898,9f5ab8de-4fa8-42be-abd0-ed572503e39f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15900,7b428b65-e5bc-4d2f-bbd1-2e17a883b6df-00121a90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15901,650dac91-a97a-4182-b882-b1b294b266e3-001aaf9c,Exhaust Air,HVAC - Exhaust Air,EA 1,EA,,450 mmx450 mm,450 mmx450 mm,0.0,...,3605.0,3380.0,3155.0,0.684,380.0,0.0,ex_KHVAC_Radius Elbows / Taps,NaN,NaN,NaN
4,15932,650dac91-a97a-4182-b882-b1b294b266e3-001ab1f3,Supply Air,HVAC - Fresh Air,FA 1,FA,,450 mmx450 mm,450 mmx450 mm,0.0,...,3605.0,3380.0,3155.0,0.684,380.0,0.0,ex_KHVAC_Radius Elbows / Taps,NaN,NaN,NaN

In [26]:
import os
dir = "./output"
if not os.path.exists(dir):
    os.makedirs(dir)
df.to_csv("./output/pipes_ducts.csv", index=False)